POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "junin_matado@email",
  "senha": "porco"
}

###

GET http://localhost:5000/userdata
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.anVuaW5fbWF0YWRvQGVtYWls.0H11hgeMRT7b3KnWOD4Qsh1dyJzxsgnldkYozZKZe_g